// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7d31JzpzdoW05AEyQQ8GYHynGj8w-M28',
    appId: '1:448887356891:web:dd9a4d21c7afd795c57bfe',
    messagingSenderId: '448887356891',
    projectId: 'hotdogfinal',
    authDomain: 'hotdogfinal.firebaseapp.com',
    storageBucket: 'hotdogfinal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKeNCbyEQfg7cQYb2F0e7XFKMUq_uaBE4',
    appId: '1:448887356891:android:ffa805e465b331adc57bfe',
    messagingSenderId: '448887356891',
    projectId: 'hotdogfinal',
    storageBucket: 'hotdogfinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz2mQJMd34M7ZQfTxtXGSF-_CRjIV6ves',
    appId: '1:448887356891:ios:105745fb426cb9ffc57bfe',
    messagingSenderId: '448887356891',
    projectId: 'hotdogfinal',
    storageBucket: 'hotdogfinal.firebasestorage.app',
    iosBundleId: 'com.example.hotdogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz2mQJMd34M7ZQfTxtXGSF-_CRjIV6ves',
    appId: '1:448887356891:ios:105745fb426cb9ffc57bfe',
    messagingSenderId: '448887356891',
    projectId: 'hotdogfinal',
    storageBucket: 'hotdogfinal.firebasestorage.app',
    iosBundleId: 'com.example.hotdogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7d31JzpzdoW05AEyQQ8GYHynGj8w-M28',
    appId: '1:448887356891:web:d8e59c82ff291618c57bfe',
    messagingSenderId: '448887356891',
    projectId: 'hotdogfinal',
    authDomain: 'hotdogfinal.firebaseapp.com',
    storageBucket: 'hotdogfinal.firebasestorage.app',
  );
}
